### ISSUE TITLE
Emails are down - no emails are going out of weezevent tools

### ISSUE THREAD

**Issue by mattgu74** [Weezevent/status-page#26]
Today at 16:00 Paris time, AWS pause our ability to send emails due to a malicious usage of one of our feature.
We are doing our best to getting back our ability to send such emails.
Majority of emails (payment confirmations / ticket deliveral) will be sent with delay, but are queued and will be processed as soon as possible.

**Comment by mattgu74** [comment]
Today at 16:00 Paris time, AWS pause our ability to send emails due to a malicious usage of one of our feature.
We are doing our best to getting back our ability to send such emails.
Majority of emails (payment confirmations / ticket deliveral) will be sent with delay, but are queued and will be processed as soon as possible.

**Comment by bmunzer** [comment]
**Resolved:** Incident is closed. 
All emails are now in queue and will be send in the next few minutes

**Comment by bmunzer** [comment]
- FR

Bonjour,
<br/>
<br/>
Notre système a rencontré Jeudi 26/01/2023 une utilisation malveillante de la part d’organisateurs ayant envoyé des e-mails considérés comme spam auprès de leur base e-mails. Nous avons identifié et bloqué les comptes de ces organisateurs. 
<br/>
<br/>
Suite à de nombreuses remontées de spam liées à l’envoi de ces e-mails, notre hébergeur a bloqué préventivement notre capacité à envoyer des e-mails entre 16h et 23h. 
<br/>
<br/>
Pendant ce temps d’interruption, les e-mails qui auraient dû être envoyés se sont placés sur une file d’attente afin d’être envoyés ultérieurement. Le déblocage de cette file d’attente a été effectué à 23h30 et tous les e-mails en attente ont été envoyés. 
<br/>
<br/>
Lors de ce déblocage, une erreur technique a malencontreusement débloqué d’autres e-mails restés dans un statut d’attente d’envoi pour des événements passés. L’impact est mesuré car notre service technique s'est aperçu rapidement de cette erreur, et a donc stoppé l'envoi de ces mails. 
<br/>
<br/>
Nous avons apporté différents correctifs et mis en place des systèmes préventifs additionnels qui permettront de ne plus rencontrer cette situation à nouveau.
<br/>
<br/>
Nous vous prions de bien vouloir nous excuser pour la gêne occasionnée.
<br/>
<br/>
Bien à vous
<br/>
<br/>
- UK

Hello,
<br/>
<br/>
Our system encountered malicious use 26/01/2023 from organizers who sent emails considered spam to their email database. We have identified and blocked the accounts of these organizers. 
<br/>
<br/>
Following large amount of spam reports related to the sending of these emails, our Email supplier preventively blocked our ability to send emails between 4 p.m. and 11 p.m. 
<br/>
<br/>
During this downtime, emails that should have been sent were placed in a queue to be sent later. This queue was unblocked at 11:30 p.m. and all pending emails were sent. 
<br/>
<br/>
During this unblocking, a technical error inadvertently unblocked other e-mails that remained in a status of waiting to be sent for past events. The impact is measured because our technical department quickly noticed this error, and therefore stopped sending these emails. 
<br/>
<br/>
We have made various fixes and implemented additional preventive systems that will prevent you from encountering this situation again. 
<br/>
<br/>
We apologize for the inconvenience caused. 
<br/>
<br/>
Sincereley,
