### ISSUE TITLE
🛑 Weezevent services experienced some slowness

### ISSUE THREAD

**Issue by darkwind-noveo** [Weezevent/status-page#55]
In [`f12976e`](https://github.com/Weezevent/status-page/commit/f12976e6134178a963f6c39d01c2e21f18858fa3
), WeezCheckpoint (https://api.weezevent.com/checkpoint) was **down**:
- HTTP code: 500
- Response time: 538 ms

**Comment by bmunzer** [comment]
# FR 

Aujourd'hui à 18h20 le 28/07/2023 (heure de paris) une mauvaise configuration a été mise en place dans notre infrastructure. Comme il s'agissait du point d'entrée, tous les services ont été touchés.

### CE QUI S'EST PASSÉ
Les alarmes et les moniteurs ont fait leur travail, les actions correctives ont été faites. L'ensemble des services étaient à nouveau opérationnel dans les 5 minutes. 
Vers 19h00, de nouveaux moniteurs et alarmes ont à nouveau été déclenchées. Il est apparu qu'un autre problème était toujours en cours.
Certaines configurations très profondes avaient également été modifiées et n'étaient pas supervisées.
les actions correctives ont été faites et nous sommes revenu à la normale vers 19h05.

### IMPACTS
Les services ont été impactés à différents niveaux. Les back-offices WeezTicket, WeezAccess, WeezTarget, WeezPay sont restés opérationnels, mais certains utilisateurs ont connu quelques lenteurs. Toutes les transactions non abouties ont été remboursées.

### ACTIONS
Tous les départements concernés prennent toutes les mesures nécessaires.



# UK

Today at 18:20 28/07/2023 (paris time) a bad configuration has been set up in our infrastructure. Because it was about the entry point, all services were impacted.

### WHAT HAPPENED
Alarms and monitors did their job and we go back online within 5 minutes. The issue was solved.
Around 19:00 some new monitors and alarms woke up and we discover that an other issue was still running.
On the same actions, some very deep configurations have been changed, too. These ones were not under supervision.
The configuration has been restored and we go back to normal around 19:05.

### IMPACTS
Services were impacted at diffrent levels. WeezTicket, WeezAccess, WeezTarget, WeezPay Back-offices were up but some users experienced some slowness. All non accomplished transactions have been refunded.

### ACTIONS
All involved departments are taking all needed actions.
